### ISSUE TITLE
Teach LLMs to Dance Salsa 🔥 

### ISSUE THREAD

**Issue by aaron-sandoval** [aaron-sandoval/Test-Repository#2]
Don't think anyone's done this. Thoughts?

**Comment by throwaway219** [comment]
Hell yes! Someone did tango but this would be 🔥🔥🔥🔥🔥🔥🔥

**Comment by zhu502846** [comment]
TBH Salsa might not be novel enough, you should look at break dancing, especially given its prominence in the 2024 olympics.
